config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/contact', to: 'home#contact', as: :contact
  get '/propos', to: 'home#propos', as: :propos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def propos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<br>
<br>
<br>
<br>
<br>

<h1> Mes coordonnées </h1>

<div class="cards-text">
<p> Vous pouvez me joindre au: 06.62.31.97.81 </p>
  <p> ou par mail à gaelle.gorgori@gmail.com </p>
  <p> ou sur slack </p>
  <p> ou par signaux de fumée </p>
  <p> ou par pigeon voyageur </p>
  <br>
</div>
<%= link_to "Retour à l'acceuil", home_path %>

app/views/home/index.html.erb
<div id='acceuil'>
  <h1>Candy Price: Soyez mieux informés que vos clients!</h1>

    <div class='part'>

             <div class='main'>

              <h3> Quels sont les indicateurs les plus importants pour un juste pricing? </h3>

     <input id='tab1' type='radio' name='tabs'>
      <label for='tab1'>La concurrence</label>

      <input id='tab2' type='radio' name='tabs'>
      <label for='tab2'>La montée en charge</label>

      <input id='tab3' type='radio' name='tabs'>
      <label for='tab3'>Le calendrier</label>

      <input id='tab4' type='radio' name='tabs'>
      <label for='tab4'>Le taux d'occupation</label>

      <input id='tab5' type='radio' name='tabs'>
      <label for='tab5'>La situation</label>

      <div class='content'>
        <div id='content1'>
        <p>
          La concurrence – Et oui! connaitre les tarifs de ses concurrents (ceux dont la prestation est identique) est indispensable pour un juste prix! Si vos concurrents sont moins chers que vous, vos clients feront leur choix.
        </p>
        </div>

        <div id='content2'>
        <p>
         La montée en charge: Sur une date donnée, vos chambres se remplissent à quel rythme? Si elles ne partent pas, c'est qu'il y a un problème de prix. Et si elles partent trop vite, aussi!
        </p>
        </div>

        <div id='content3'>
        <p>
          Le calendrier: Il va de soi que vous ne pratiquez pas les mêmes tarifs en période de vacances scolaires et en dehors des vacances scolaires. Il est important de pratiquer des prix spéciaux sur les vacances, les jours fériés, mais aussi sur les dates qur lesquelles des événements sont organisés dans la ville.
        </p>
        </div>

        <div id='content4'>
        <p>
         Le taux d'occupation: Il est à surveiller en permanence, sur toutes les dates. Plus votre établissement est chargé à une date et plus le prix doit grimper. La rareté fait le prix!
        </p>
        </div>
        <div id='content5'>
        <p>
         La situation: Etes-vous proche de la mer? des transports en commun? des lieux de sorties nocturnes? des centres d'affaires? Le positionnement géographique de l'hotel peut grandement influer sur le prix des chambres.
        </p>
        </div>
      </div>

      </div>
      </div>


    <div class='part'>
    <!-- Mise en place des cards, leur css associé se trouve dans styleshhet/card.css -->
             <div id='leftpart'>

                    <div class='cards'>

                        <div id='pub'>

                           <div class='card'> <%= image_tag('beach.jpg', alt: 'beach', :class => 'card') %>
                             <div class='card-user'> <%= image_tag('gaga.jpg', alt: 'moi', :class => 'rounded-circle img-raised') %>
                            </div>
                            <div class='card-tag'> #Revenue manager
                            </div>
                            <div class='card-description'>
                            <h3>Aux hoteliers : </h3>
                            <p> Amenez les clients vers votre hotel!</p>
                            </div>
                         </div>
                         <div class='card'> <%= image_tag('hotel.png', alt: 'hotel', :class => 'card') %>
                            <div class='card-user'> <%= image_tag('kaka.jpg', alt: 'directeur', :class => 'rounded-circle img-raised') %>
                            </div>
                             <div class='card-tag'> #hotelier
                            </div>
                             <div class='card-description'>
                            <h3>A mes clients : </h3>
                             <p> Nos tarifs sont justes!</p>
                            </div>
                         </div>
                       </div>
<!-- Mise en place des boutons, leur css associé se trouve dans styleshhet/button.css -->
                <div class='cards'>
                    <div id='boutons'>
                          <div class='bouton1'>
                          <button class='btn btn-success'><%= link_to 'En savoir plus', propos_path %> </button>
                        </div>
                        <div class='bouton1'>
                          <button class='btn btn-warning'> <%= link_to 'Me contacter', contact_path %> </button>
                        </div>
                    </div>
              </div>
          </div>
    </div>
  </div>
</div>

<br> <br> <br> <br>

app/views/home/propos.html.erb
<br>
<br>
<br>
<br>
<br>

<h1> A propos de moi </h1>
<div class="cards-text">
<p> Plus de 10 ans d'expérience réussie dans le revenue management </p>
  <p> Les secteurs dans lesquels j'ai travaillé: chaines hotelières, tour-opérateur, agences de voyage </p>
  <p> Formation: Mathématiques appliquées </p>
  <p> Mes hobbies: les tableaux de bord! </p>
<br>
</div>

<%= link_to "Retour à l'acceuil", home_path %>

app/views/layouts/_footer.html.erb
<ul id="foot">
    <li id="foot-reseaux"> Contactez-moi sur les réseaux sociaux: </li>
    <li id="foot-facebook"><a href="https://www.facebook.com/gaelle.gorgori"><%= image_tag 'logo_facebook.png', :class => 'rounded-circle-res' %></a></li>
    <li id="foot-linkedin"><a href="https://www.linkedin.com/in/ga%C3%ABlle-gorgori-55394a26/"><%= image_tag 'logo_linkedin.png', :class => 'rounded-circle-res' %></a></li>
    <li id="foot-twitter"><a href="https://twitter.com/GGalle8"><%= image_tag 'logo_twitter.png', :class => 'rounded-circle-res' %></a></li>
    <li id="foot-contact"> Made with ❤️ at Saint-Laurent-du-Var </li>
</ul>

app/views/layouts/_header.html.erb
    <ul id="nav">
        <li id="nav-home"><%= image_tag 'logo.JPG', :class => 'rounded-circle img-raised'%> </li>
        <li id="nave-name"> © Candy price </li>
        <li id="nav-about"><a href="https://fr.wikipedia.org/wiki/Benchmarking"> Le Bench </a></li>
        <li id="nav-exp"><a href="http://www.e-marketing.fr/Thematique/management-1090/Breves/Fiche-metier-est-analyste-revenue-manager-308258.htm#mPOPsaHpCtkxJ1u1.97"> Le métier RM </a></li>
        <li id="nav-expert"><a href="https://www.liligo.fr/hotels.html"> L'exemple B2C </a></li>
        <li id="avatar">
        <div class="dropdown">
            <button class="rounded-circle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= image_tag 'gaga.jpg', :class => 'rounded-circle img-raised' %> </button>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" x-placement="top-start" >
                     <li> Hello</li>
                     <li> Qui veut faire</li>
                    <li> ce projet avec moi ?</li>
                    </ul>
                  </div>
         </li>
      </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetCssGg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container wrapper">
     <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>